config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :tweets, only: [:index, :new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :message, length: { maximum: 400 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tweets
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    tweets_path
  end
end

app/controllers/tweets_controller.rb
require 'telegram/bot'
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:destroy]

  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    if @tweet.save!
      redirect_to tweets_path
    else
      render :new
    end
    # token = "1766018784:AAH5_x_sRAhU32B_CKkgMR6EjtayVUYM1Qw"
    # Telegram::Bot::Client.run(token) do |bot|
    #   bot.listen do |message|
    #     bot.api.send_message(chat_id: message.chat.id, text: "#{@tweet.message}")
    #   end
    # end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/covid_helper.rb
module CovidsHelper
  def home
      @data = JSON.parse(RestClient.get "https://api.covid19api.com/live/country/argentina/status/confirmed/date/2020-03-21T13:13:30Z")
  end
  
  def fetch_country
    RestClient.get "https://api.covid19api.com/live/country/argentina/status/confirmed/date/2020-03-21T13:13:30Z"
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if user_signed_in? %>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <%= link_to "Disconnect", destroy_user_session_path, class: "nav-link", method: :delete %>
        </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FsTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/4fb0f37437.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/tweets/_new.html.erb
<div class="modal fade" id="tweetModal" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="tweetModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h5 class="modal-title" id="tweetModalLabel">Crear tweet</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for @tweet do |f| %>
        <div class="modal-body">
            <div id="formulario" class="container-fluid text-center">
              <div class="form-inputs">
                <div class="row">
                  <div class="col-md-12">
                    <%= f.input :message,  :label => "Qué quieres twittear?", placeholder:"Máximo 400 carácteres."%>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <div class="modal-footer d-flex justify-content-around">
          <div class="form-actions">
            <button type="button" class="btn btn-secondary pt-2" data-dismiss="modal">Cerrar</button>
            <%= f.submit "Crear tweet!", class:"btn btn-primary mr-3" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8">
      <button class="btn btn-primary" data-toggle="modal" data-target="#tweetModal">
        <i class="fab fa-twitter"></i> Crear Tweet
      </button>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8" >
      <h2 class="my-3">Todos los tweets</h2>
      <div class="cards">
        <% if @tweets.any? %>
          <% @tweets.each do |tweet| %>
            <div class="my-3">
              <div class="card-product">
                <%= tweet.message %>
                <%= link_to tweet_path(tweet), method: :delete, data: { confirm: "Are you sure?"} do %>
                  <i class="fas fa-trash"></i>
                <% end %>
              </div>
            </div>
          <% end %>
        <% else %>
          <div>Aun no hay ningún tweet</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render 'new' %>